### ISSUE TITLE
EntitySet Naming

### ISSUE THREAD

**Issue by jlattimer** [DigitalFlow/Xrm-WebApi-Client#1]
The way you're determining the entity set name isn't always accurate. There are a number of instances where entities don't follow the "standard" conventions. Granted these are rarely used intersect entities, but you'll notice in the examples I've included the EntitySetName appends 'set' or 'collection'. Really the best way to determine the value is to go to the metadata ad find the value. 

![image](https://cloud.githubusercontent.com/assets/1769982/19784546/c869c1d6-9c5b-11e6-9930-52ccb10448d3.png)

![image](https://cloud.githubusercontent.com/assets/1769982/19784554/cdaf947c-9c5b-11e6-9f38-10566940ebe3.png)

**Comment by DigitalFlow** [comment]
Hey there,

Thanks for your issue.
Since this does not seem to follow a rule, what do you think about adding the possibility to specify the set name on requests for overriding the automatically generated set names?

Kind Regards,
Florian

**Comment by jlattimer** [comment]
I think that is probably a good option. Making a metadata request to the fly to get it would be costly in terms of performance and trying to maintain a hard-coded list would get ugly.

**Comment by DigitalFlow** [comment]
Just published a new release that addresses this issue, I will close it therefore.
