### ISSUE TITLE
Can't create RetrievePrincipalAccessRequest

### ISSUE THREAD

**Issue by fvakiliev** [DigitalFlow/Xrm-WebApi-Client#15]
Hi @DigitalFlow !

I Cat't create **_RetrievePrincipalAccessRequest_**. Please give me en example.

Regards,
FV

**Comment by DigitalFlow** [comment]
Hey @fvakiliev,

I added an [example](https://github.com/DigitalFlow/Xrm-WebApi-Client/wiki/Implemented-WebApi-Requests#retrieveprincipalaccess) for executing the request to the Wiki.
Hope this helps.

Kind Regards,
Florian

**Comment by fvakiliev** [comment]
Thank you very much, Florian!

**Comment by DigitalFlow** [comment]
You're very welcome Firat :)
