### ISSUE TITLE
Question about using API from a web page

### ISSUE THREAD

**Issue by whitneyland** [DigitalFlow/Xrm-WebApi-Client#17]
Can the API be used to access CRM data like users, sales pipeline, etc, from a normal HTML web site?

Please forgive the ignorance, but I'm not sure what you mean here:
> The framework is supposed to be executed on CRM forms or on CRM web ressources, where the CRM context is available

I'm just looking for the simplest way to use JavaScript to get data from 
https://\<mycompany>.crm.dynamics.com/api/data/v8.0/

**Comment by DigitalFlow** [comment]
Hey there,

Right now it can only be used on CRM WebResources and forms.
Adding authentication for external sites is work in progress right now.

Kind Regards,
Florian

**Comment by DigitalFlow** [comment]
I'll close this for now, as I'll need to open an enhancement issue as soon as I have an Azure AD for testing.

**Comment by DigitalFlow** [comment]
Hey @whitneyland,

Sorry for the delay.
Usage from an external website is now possible.

Kind Regards,
Florian
