### ISSUE TITLE
WebApiClient.js is not loaded on Mobile version because of conflict with existing bluebird.js

### ISSUE THREAD

**Issue by khorozhansky** [DigitalFlow/Xrm-WebApi-Client#19]
Hello,
Looks like WebApiClient.js is not loaded on Mobile version (both phone and tablet) because of conflict with existing bluebird.js (which is loaded by default for mobile).
Version: Dynamics 365 (Version 1612 (8.2.1.207) (DB 8.2.1.207) online)
Do you have any workaround for making it working on Mobile?
Thank you

**Comment by khorozhansky** [comment]
It seems the following workaround works. Add "noConfilct()" below:
...
    // Attach bluebird to WebApiClient
    WebApiClient.Promise = require("bluebird")**.noConflict();**
...

**Comment by DigitalFlow** [comment]
Hey there,

Thanks for creating this issue (and delivering the solution as well 😄 ).

I just published v3.4.2, which loads bluebird using the noConflict function.
Can you check, whether this solves your problem?

Kind Regards,
Florian

**Comment by khorozhansky** [comment]
Hi Florian,
Sorry, only now continued with this, and it seems this workaround does not work always. It works on one environment and does not work on another. When it works it seems there is an issue inside anyway, just do not receive error message

**Comment by DigitalFlow** [comment]
Hi @khorozhansky,

Are you using the minified code?
I experienced that the minified version was causing issues in the CRM app, while the normal one did work properly. 
I also wrote a section in the read me regarding this [here](https://github.com/DigitalFlow/Xrm-WebApi-Client#crm-app).
Can you test, whether the not minified version works?

Kind Regards,
Florian

**Comment by khorozhansky** [comment]
Yes seems the issue in minified file. I've just tried not minified version and it works.
Then I tried to use https://github.com/madskristensen/BundlerMinifier Visual Studio extention to make the minified version and it also looks working. Thanks

**Comment by DigitalFlow** [comment]
Hey @khorozhansky,

Great that it's working now.
I'll close this issue but will have to check why uglifyjs and CRM don't like each other.

Kind Regards,
Florian
