### ISSUE TITLE
[Question] WebApiClient intellisense

### ISSUE THREAD

**Issue by phuocle** [DigitalFlow/Xrm-WebApi-Client#20]
Please help me how I can get intellisense for WebApiClient in my Visual Studio 2017

Thanks

**Comment by DigitalFlow** [comment]
Hey @phuocle,

Are you using TypeScript or plain JS?

For TypeScript typings are shipped with the code, you'll just have to import 'xrm-webapi-client'.
For plain JS you'll need to add WebApiClient non-minified to your project and in all scripts where you need it, add a reference tag at the very top.

This might look like this:
`XML
/// <reference path="WebApiClient.js" />
`
This is a relative file path, you'll have to adjust it to the location where you saved it.

Kind Regards,
Florian

**Comment by DigitalFlow** [comment]
Hey @phuocle,

I guess you got it working?
I'll close this issue, please reopen if it did not work out for you.

Kind Regards,
Florian
