### ISSUE TITLE
WebApiClient is undefined

### ISSUE THREAD

**Issue by aboodh95** [DigitalFlow/Xrm-WebApi-Client#25]
Hi

i don't know why this is happening but I'm getting WebApiClient is undefined, i replace the [PathToWebApiClient] with the file path and everything suppose to work but i'm getting this error 
ReferenceError: WebApiClient is not defined

**Comment by DigitalFlow** [comment]
Hey there,

What is your setup? Are you trying to use it on a form?
Which browser are you using?

Kind Regards, 
Florian

**Comment by aboodh95** [comment]
Hi

I was testing the SinglePageApp file 
i'm using Chrome and firefox 
i tried local server and public server 
the main problem was the Require function not working after i add the require library i'm getting new error 
Error: Mismatched anonymous define() module: function () {

    var define, module, exports; return function e(t, n, r) { function s(o, u) { if (!n[o]) { if (!t[o]) { var a = typeof require == "function" && require; if (!u && a) return a(o, !0); if (i) return i(o, !0); var f = new Error("Cannot find module '" + o + "'"); throw f.code = "MODULE_NOT_FOUND", f } var l = n[o] = { exports: {} }; t[o][0].call(l.exports, function (e) { var n = t[o][1][e]; return s(n ? n : e) }, l, l.exports, e, t, n, r) } return n[o].exports } var i = typeof require == "function" && require; for (var o = 0; o < r.length; o++) s(r[o]); return s }({

        1: [function (require, module, exports) {

            (function (process, global) {/* @preserve
 * The MIT License (MIT)
 * 
 * Copyright (c) 2013-2017 Petka Antonov
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without …

is there any specific release from Require library should be loaded

**Comment by DigitalFlow** [comment]
Hey there,

you should use the latest (minified) release from the [releases page](https://github.com/DigitalFlow/Xrm-WebApi-Client/releases).

**Comment by DigitalFlow** [comment]
Hey @aboodh95,

Did you get it to work?

Kind Regards, 
Florian

**Comment by aboodh95** [comment]
Hi

Yes it's working 

Thank you so much
