### ISSUE TITLE
HELP: How to retrieve OptionSet's

### ISSUE THREAD

**Issue by fvakiliev** [DigitalFlow/Xrm-WebApi-Client#28]
Hi Florian,

Please send example for how to retrieve lists of Global/Local OptionSet's and StatusReasons (statuscode).
Like there:
`https://<crm-org>/api/data/v8.2/GlobalOptionSetDefinitions(Name='cp_opportunityreasonsoflost')`

Thanks,
OldCat

**Comment by DigitalFlow** [comment]
Hi @fvakiliev,
 
I did that using WebApiClient in [here](https://github.com/DigitalFlow/Xrm-Quick-Edit/blob/master/src/js/Translator/OptionSetHandler.js#L160).
You can basically just copy it, Xrm-Quick-Edit is retrieving the option sets in the translation dashboard.
You can try it out using the Option Set translation option for an entity.

I'll close this issue, please reopen if you need more information.

Kind Regards,
Florian
