### ISSUE TITLE
TypeError: WebApiClient.ChangeSet is not a constructor

### ISSUE THREAD

**Issue by garciasa** [DigitalFlow/Xrm-WebApi-Client#32]
Hi there,
I'm building a custom component for CRM 365, and I'm using this nice library :).
When I'm using Batch functionality, I'm getting the following error:
**TypeError: WebApiClient.ChangeSet is not a constructor**
This is function I'm using:
```
export const saveFrequencies = qualityElements => {
  const reqs = [];
  qualityElements.forEach(qe => {
    const req = WebApiClient.Update({
      entityName: 'wfd_monitoringprogrammefrequency',
      entityId: qe.id,
      entity: {
        wfd_year1frequency: parseInt(qe.year1frequency) || 0,
        wfd_year2frequency: parseInt(qe.year2frequency) || 0,
        wfd_year3frequency: parseInt(qe.year3frequency) || 0,
        wfd_samplingperiod: qe.samplingperiod,
      },
      asBatch: true,
    });
    reqs.push(req);
  });

  const chSets = new WebApiClient.ChangeSet({
    requests: reqs,
  });

  const batch = new WebApiClient.Batch({
    changeSets: [chSets],
  });

  return WebApiClient.SendBatch(batch);
};
```

The batch updates work (those records are updated in CRM), but then my component fails, since I get that javascript error.

I'm using Chrome last version or Firefox last version.

Any Idea?

**Comment by DigitalFlow** [comment]
Hey there,

the ChangeSet constructor looks fine. If the update is being sent to CRM as well, then this can't be your issue location.
Can you check whether you tried to instantiate a change set somewhere after the call succeeds?

Kind Regards,
Florian

**Comment by garciasa** [comment]
Hi Florian,
No, I didn't instantiate a change set after the call as far as I know :).
At the moment I've changed the batch, for an array of regular Updates and I manage them with Promise.all.
That at least works without type error.

Cheers,
Antonio.

**Comment by DigitalFlow** [comment]
Hi @garciasa,

I'll close this task as it seems to have caused no further issues to you.
If it does, please paste a minimum working example on a CRM default entity (such as account) and reopen this issue.

Kind Regards,
Florian
