### ISSUE TITLE
Error on retrieve usersettingscollection entity

### ISSUE THREAD

**Issue by fvakiliev** [DigitalFlow/Xrm-WebApi-Client#35]
Hi Florian!

When I retrieve usersettingscollection entity, I have error:

```
var userSettings = WebApiClient.Retrieve({                
            entityName: "usersettingscollection",
            entityId: currentUser.replace("{", "").replace("}", ""),
            queryParams: '?$select=decimalsymbol,numberseparator',
            async: false
        });

"code":"","message":"Resource not found for the segment 'usersettingscollections'."

```
I think that entity plural name **usersettingscollections** is wrong. Should be **usersettingscollection**

Regards
OldCat

**Comment by DigitalFlow** [comment]
Hi @fvakiliev,

Yes, you're right, the name of the entity set is _usersettingscollection_, without the pending s.
The library uses the default rules for building collection names from entity names, unfortunately CRM chose to use different collection names for some special entities.

For those exceptions, don't pass the entityName, and use `overriddenSetName` instead, as described [here](https://github.com/DigitalFlow/Xrm-WebApi-Client#set-names):
```JS
var userSettings = WebApiClient.Retrieve({                
            overriddenSetName: "usersettingscollection",
            entityId: currentUser.replace("{", "").replace("}", ""),
            queryParams: '?$select=decimalsymbol,numberseparator',
            async: false
        });
```
In addition to that: Please remember that using async: false is discouraged if you don't really need to, so if possible in any way, please use the promise style.

**Comment by fvakiliev** [comment]
Thanks!
