### ISSUE TITLE
Can't create RetrievePrincipalAccessRequest with typescript

### ISSUE THREAD

**Issue by methodnumber13** [DigitalFlow/Xrm-WebApi-Client#36]
I'm trying to make request with typescript like this:
` try {
        let req = new webapi.Requests.RetrievePrincipalAccessRequest()
        .with({ 
            entityName: 'systemuser',
            entityId: toTrimBrackets(parent.Xrm.Page.context.userSettings.userId),
            urlParams: {
                Target: `{"@odata.id": "accounts('${id}')"}`
            }
        });
        console.log(req);
        webapi.Execute(req)
        .then((result: any) => {
        console.log(result);
        });

    } 
    catch (e) {console.error(e)}`
and I got this error 
![image](https://user-images.githubusercontent.com/26242969/56027432-b8a90f00-5d1e-11e9-956f-7f7dfca87c5f.png)

Also, I tried to write it like 
` let req = webapi.Requests.RetrievePrincipalAccessRequest;
req.prototype.with({///my code here})
`
and I got another error
![image](https://user-images.githubusercontent.com/26242969/56027876-95329400-5d1f-11e9-86c7-36a520f05568.png)
Could you provide any samples how I can make my request correctly?

P.S.: I have already seen an implementation with JS from this link [https://github.com/DigitalFlow/Xrm-WebApi-Client/wiki/Implemented-WebApi-Requests](url)
but it's not working in TS

**Comment by DigitalFlow** [comment]
Hi @methodnumber13,

Thanks for reaching out.
Can you please try leaving out the "new" in front of the request and not appending the parentheses, so that it looks like this:
```let req = webapi.Requests.RetrievePrincipalAccessRequest.with(...)```

The requests are not regular classes, they are objects which get their messages and properties by protoypal inheritance.

Kind Regards,
Florian

**Comment by DigitalFlow** [comment]
Hi @methodnumber13,

I'll close this issue for now, if above fix does not solve your issue, please reopen again.

Kind Regards,
Florian
