### ISSUE TITLE
returnAllPages = true

### ISSUE THREAD

**Issue by phuocle** [DigitalFlow/Xrm-WebApi-Client#37]
Hi @DigitalFlow 

Yesterday our FetchXml request has setting ```returnAllPages = true;``` and it ok. The return result about 2,000 rows, but we understand in feature it maybe more than 5,000 rows that why we set this value.

But today, i get an error when execute the same query, I'm sure nothing change from yesterday.
Now, if I change the setting ```returnAllPages = false;``` and it ok again. wwowowow.

Look at the core js and i found maybe something wrong in the checking condition
```js
...
            var nextLink = GetNextLink(response);
            var pagingCookie = GetPagingCookie(response);
            response = MergeResults(parameters._previousResponse, response);
            // Results are paged, we don't have all results at this point
            if (nextLink && (WebApiClient.ReturnAllPages || parameters.returnAllPages)) {
                SetPreviousResponse(parameters, response);
                SendSync("GET", nextLink, null, parameters);
            }
            else if (pagingCookie && (WebApiClient.ReturnAllPages || parameters.returnAllPages)) {
                var nextPageFetch = SetCookie(pagingCookie, parameters);
                SetPreviousResponse(parameters, response);
                parameters.fetchXml = nextPageFetch;
                WebApiClient.Retrieve(parameters);
            }
}
```

The first ```if``` passed because the ```nextlink``` is ```undefined```
The second ```else if``` will run because ```pagingCookie``` now have value with setting ```returnAllPages = true;``` or ```returnAllPages = false;``` and the ```exception``` throw in the method ```SetCookie```

I guest something change from the response, so the function ```GetPagingCookie``` always has data.

Note: I'm using ```async = false;```, return rows <2,000 rows, setting ```returnAllPages = true;```
 
Please help review my issue and thanks for a great WebApi, we love it and use it in all company projects.

**Comment by DigitalFlow** [comment]
Hey @phuocle,

I'm glad that you use the library and that you like it, thanks for that :smile:

I'd like to reproduce your issue at my side, for that I need you to give me the following information:
- Version of the CRM Organization where you're having issues
- Snippet of the WebApi query that you're trying to execute on one of the default entities, such as account.

I'd then try to reproduce the issue and provide a bugfix if I find any incorrect behaviour.

Kind Regards,
Florian

**Comment by phuocle** [comment]
Hi @DigitalFlow , please use the following code
```js
var formAccount = (function () {
	function onLoad(executionContext) {
		var failRequest = getRequest(true);
		debugger;
		var response = WebApiClient.Retrieve(failRequest);
		alert("CAN GET RESPONSE !!!!");
	}
	function onSave(executionContext) {
		var okRequest = getRequest(false);
		debugger;
		var response = WebApiClient.Retrieve(okRequest);
		alert("CAN GET RESPONSE !!!!");
	}

	function getRequest(returnAllPages){
		var fetchXml = [
			"<fetch version='1.0' output-format='xml-platform' mapping='logical' distinct='false'>",
			"  <entity name='account'>",
			"    <attribute name='name'/>",
			"    <attribute name='primarycontactid'/>",
			"    <attribute name='telephone1'/>",
			"    <attribute name='accountid'/>",
			"    <order attribute='name' descending='false'/>",
			"  </entity>",
			"</fetch>",
				].join("");
		var request = {};
		request.entityName = "account";
		request.fetchXml = fetchXml;
		request.async = false;
		request.returnAllPages = returnAllPages;
		return request;
	}
	return {
		OnLoad: onLoad,
		OnSave: onSave
	};
})();
```
**NOTE**
* I use latest version ```v.3.6.11```

**Comment by gasyleiss** [comment]
Hi @DigitalFlow 
I have the same issue as @phuocle...
Regards,
Njaka

**Comment by DigitalFlow** [comment]
Hi @gasyleiss,

thanks for reporting.
Can you please state your exact CRM version for me being able to reproduce the issue?

Kind Regards,
Florian

**Comment by daimaah** [comment]
For me this is happening with the version 1710 (9.1.0.4044) online.

**Comment by DigitalFlow** [comment]
Thanks for the information, I'll get on it this evening :+1:

**Comment by DigitalFlow** [comment]
Hi @phuocle / @gasyleiss / @daimaah,

I found the issue: On new online organizations, MS is now only escaping their paging cookies once, whereas they double escaped their paging cookies previously, so that we had to unescape them twice as well.

Example Old Paging Cookie:
`%253ccookie%2520page%253d%25221%2522%253e%253cname%2520last%253d%2522asdfasdfasdf%2522%2520first%253d%2522asdfasdfasdf%2522%2520%252f%253e%253caccountid%2520last%253d%2522%257b38554D80-FED9-E811-80EE-0050568E4745%257d%2522%2520first%253d%2522%257b38554D80-FED9-E811-80EE-0050568E4745%257d%2522%2520%252f%253e%253c%252fcookie%253e`

Examplew New Paging Cookie:
`%3ccookie%20page%3d%221%22%3e%3cname%20last%3d%22Zydus%20Pharmaceuticals%20%28USA%29%20Inc.%22%20first%3d%22123123%20Updated%20Name%202341234%22%20%2f%3e%3caccountid%20last%3d%22%7b3F97EEA8-7CE4-E611-80F8-5065F38B3681%7d%22%20first%3d%22%7b1D834831-A073-E711-810B-E0071B65ED51%7d%22%20%2f%3e%3c%2fcookie%3e`

It's very cryptic, but basically you need to unescape the old cookie twice for getting valid XML, whereas you only need to do it once with the new one.

Version 3.6.12 was published right now, which adds a fix for handling both single and double escaped paging cookies.

Thanks for all of your feedback and sorry for the slight delay.

Kind Regards,
Florian

**Comment by phuocle** [comment]
Why Microsoft do that, a small changes but break a lot of code already deployed to production (included my project in this case).

Thanks @DigitalFlow , we now update the code. But I already fixed this bug in our dev and has busy that I cannot make a PR to your repo. Our client want the code should fixed and come from your official github.

Updating now and testing .....

**Comment by daimaah** [comment]
I'm using a different syntax for the retrieve, like this:

>         WebApiClient.Retrieve(
>             {
>                 entityName: "incident",
>                 queryParams: "?$select=ticketnumber,modifiedon,createdon,incidentid,title&$orderby=createdon desc",
>                 returnAllPages: true,
>                 headers: [
>                     { key: "Prefer", value: 'odata.include-annotations="*"' },
>                     { key: "OData-MaxVersion", value: "4.0" },
>                     { key: "OData-Version", value: "4.0" }
>                 ]
>             })

and now I'm getting error 400 with the following message:

> {"error":{"code":"0x80040201","message":"Invalid XML.","innererror":{"message":"Invalid XML.","type":"Microsoft.Crm.CrmException","stacktrace":"   at Microsoft.Crm.Query.EntityExpression.ExtractPlatformName(String fetchXml, XElement element)\r\n   at Microsoft.Crm.Query.EntityExpression.PlatformEntityNameFromFetchXml(String fetchXml, XElement element, DynamicMetadataCache dynamicCache, IOrganizationContext orgContext)\r\n   at Microsoft.Crm.Query.EntityExpression.InternalFromFetch(String fetchXml, DynamicMetadataCache dynamicCache, IUserAndOrganizationContext userAndOrganizationContext, ParsingConditionValuesOption parsingOption, Boolean skipMissingAttributes)\r\n   at Microsoft.Crm.Extensibility.OData.CrmODataServiceDataProvider.ExecuteQueryForEntitySet(CrmODataExecutionContext context, String entitySetName, CustomQueryOptions queryOptions, String fetchXml)\r\n   at Microsoft.Crm.Extensibility.OData.CrmODataServiceDataProvider.RetrieveEdmEntityCollection(CrmODataExecutionContext context, String entityCollectionName, String castedEntityName, ODataQueryOptions queryOptions)\r\n   at Microsoft.Crm.Extensibility.OData.EntityController.GetEntitySetImplementation(String entitySetName)\r\n   at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute[TResult](ILogger logger, EventId eventId, ActivityType activityType, Func`1 func, IEnumerable`1 additionalCustomProperties)\r\n   at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.Execute[TResult](ILogger logger, XrmTelemetryActivityType activityType, Func`1 func)\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()","internalexception":{"message":"Data at the root level is invalid. Line 2, position 99.","type":"System.Xml.XmlException","stacktrace":"   at System.Xml.XmlTextReaderImpl.Throw(Exception e)\r\n   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()\r\n   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()\r\n   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)\r\n   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)\r\n   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)\r\n   at Microsoft.Crm.Platform.Server.Utility.XmlHelper.LoadXmlInfo(String xmlInfo)\r\n   at Microsoft.Crm.Query.EntityExpression.ExtractPlatformName(String fetchXml, XElement element)"}}}}

**Comment by DigitalFlow** [comment]
@daimaah 
That's strange, query params should use the odata,. NextLink instead of the paging cookie.
Is this error new with 3.6.12?
I'll be able to take a look this evening.

Kind Regards,
Florian

**Comment by daimaah** [comment]
Yes, this is happening with the new version 3.6.12.

**Comment by DigitalFlow** [comment]
Did it happen with 3.6.11 as well?

**Comment by daimaah** [comment]
With 3.6.11 and using the same syntax as above, all requests (all pages) are successful, but console returns the following error:

> Uncaught TypeError: Cannot read property '1' of null
>     at SetCookie (WebApiClient.min.js:56)
>     at XMLHttpRequest.xhr.onload (WebApiClient.min.js:56)
(or line 6461 in the non-minified version)

**Comment by DigitalFlow** [comment]
@daimaah,
The latest API responses now even send a fetchXml PagingCookie, if they were not fetch but queryParams requests.

In addition to that, queryParam responses return a property "@Microsoft.Dynamics.CRM.morerecords", while fetchXml responses lack these.

Futhermore, queryParam requests now don't even send an odata.nextLink anymore if there are more pages, only "@Microsoft.Dynamics.CRM.morerecords: true" and the fetchXml paging cookie.

The [SDK](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/query-data-web-api) still states, that queryParam responses should return an odata.nextLink.

I just published v3.6.13, which gets rid of your queryParams error message, but returnAllPages currently does not work for queryParam requests, as the API responses lack the odata.nextLink which we need for paging.
With the SDK still referencing the odata.nextLink for paging, it seems the current CRM patch is buggy, we'll probably have to wait for MS to release an updated version.

During this time, queryParam requests with returnAllPages will not retrieve more than 5000 pages, but at least they won't fail anymore. If you really need to retrieve more than 5000 records, you currently need to use fetchXml queries.

Kind Regards,
Florian

**Comment by daimaah** [comment]
It works now with v3.6.14. Thanks for the quick fix.

**Comment by gasyleiss** [comment]
Hello Florian,
Thank you for your great framework! ;)
Regards,
Njaka
